packages:
  - packages/*
  - docs
  - test
  - test/*
  - scripts/*
  - examples/*
  - playground/*

onlyBuiltDependencies:
  - '@mui/internal-babel-plugin-display-name'
  - '@vvago/vale'
  - core-js
  - esbuild
  - nx
  - sharp
  - unrs-resolver

patchedDependencies:
  '@atlaskit/pragmatic-drag-and-drop@1.7.9': patches/@atlaskit__pragmatic-drag-and-drop@1.7.9.patch

engineStrict: true
